### ISSUE TITLE
Standardize all flows to .yaml instead of .yml

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/blueprints#1]
Given kestra is super oriented on YAML, we should ideally standardize on the true correct extension which is `.yaml` rather than the abbreviated `.yml ` 😄

@brian-mulier-p you could run:

```yaml
#!/bin/bash

# Loop through all .yml files in the current directory
for file in *.yml; do
  # Check if the file exists to avoid errors if no .yml files are found
  if [ -e "$file" ]; then
    # Rename the file by replacing the .yml extension with .yaml
    mv "$file" "${file%.yml}.yaml"
  fi
done
```

if you prefer to keep .yml, no problem, just close the issue 👍 the .yaml seems more "correct" so given it's not released yet, we can change

**Comment by brian-mulier-p** [comment]
Done, will be good on the next sync that I'll do today
