### ISSUE TITLE
Some blueprints have inputs which show up as tasks used in blueprints

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/blueprints#4]
Example: https://kestra.io/blueprints/request-resources

![image](https://github.com/user-attachments/assets/94367fcb-05a8-4a05-969a-e085393ee2a4)

**Comment by anna-geller** [comment]
that blueprint now really went crazy 😄 

![image](https://github.com/user-attachments/assets/380d2a05-203f-4d72-ae76-784f700efbe9)

fixed this here https://github.com/kestra-io/blueprints/commit/cc1437546b40e06ca1072a322fbea97a68309242

but for the BOOLEAN and STRING, @brian-mulier-p could you have a look or delegate? 🙏 

alternatively, maybe let's remove that blueprint and create a new one with a new ID to fix it quickly?

**Comment by brian-mulier-p** [comment]
I'll have a look

**Comment by brian-mulier-p** [comment]
fixed, due to the resumeOn property that has some inputs with `type` field, I added an exception for it
